import type { Metadata } from "next";
import "@/styles/global.css"
import { AnimatePresence } from "motion/react";
import { StoreProvider } from "@/providers/StoreProvider";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Boilerplate Next TS V2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Suspense>
          <StoreProvider>
            <AnimatePresence initial={false} mode="wait">
            {children}
            </AnimatePresence>
          </StoreProvider>
        </Suspense>
      </body>
    </html>
  );
}
